# Generated by Django 5.0.1 on 2024-01-10 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable'), ('liquid', 'Liquid'), ('fixed', 'Fixed'), ('current', 'Current'), ('non_current', 'Non-current')], max_length=255)),
                ('close_method', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('detail', 'Detail'), ('regular', 'Regular')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=255)),
                ('reconcile', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('deprecated', models.BooleanField(default=False)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountingapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('from_prefix', models.CharField(max_length=255)),
                ('to_prefix', models.CharField(max_length=255)),
                ('accounts', models.ManyToManyField(to='accountingapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('bank', 'Bank'), ('general', 'General')], max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('default_credit_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_credit_account', to='accountingapi.account')),
                ('default_debit_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_debit_account', to='accountingapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('appl_ids', models.ManyToManyField(to='accountingapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapi.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='tax_ids',
            field=models.ManyToManyField(to='accountingapi.accounttax'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapi.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapi.rescompany'),
        ),
    ]
