# Generated by Django 5.0.1 on 2024-01-18 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.RemoveField(
            model_name='accountjournal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='type',
        ),
        migrations.CreateModel(
            name='AccountMoveLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapi.account')),
                ('move_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapi.accountmove')),
            ],
        ),
        migrations.AddField(
            model_name='accountmove',
            name='line_ids',
            field=models.ManyToManyField(to='accountingapi.accountmoveline'),
        ),
    ]
