# Generated by Django 5.0.1 on 2024-01-18 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapi', '0002_remove_account_type_remove_accountjournal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmove',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
