# Generated by Django 5.0.1 on 2024-01-21 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapi', '0004_accountmove_journal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountingapi.accountcategory'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapi.report'),
        ),
    ]
