# Generated by Django 5.0.1 on 2024-01-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapi', '0005_accountcategory_report_accounttype_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttax',
            name='account_id',
        ),
    ]
